[package]
name = "treemux"
version = "0.1.0"
authors = ["Ivan Porto Carrero <ivan@flanders.co.nz>"]
edition = "2018"
description = "A high performance HTTP request router that scales well."
categories = ["web-programming::http-server", "network-programming", "algorithms"]
keywords = ["hyper", "path", "tree", "radix", "router"]
repository = "https://github.com/casualjim/rs-treemux/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matchit = "0.2"
anyhow = "1"
tokio = "1"

[dependencies.hyper]
version = "0.14"
features = ["server", "tcp", "http1", "http2"]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
